eleventy.config.js, src/_includes/layouts/page.njk, src/_includes/layouts/post.njk, src/_includes/partials/components/brand.njk, src/_includes/partials/global/footer.njk, src/admin/config.yml, src/filters/date-filter.js, src/filters/w3-date-filter.js, src/index.md, src/posts/continuing-our-work-during-covid-19.md, src/posts/posts.json, src/scss/base/_base.scss, src/scss/pages/_generic.scss
Add news section on homepage, news item for COVID-19 post.
1. Visit home page, navigate to "Continuing Our Work During COVID-19".
**Expected behavior:** Home page layout and post layout matches [designs](https://www.figma.com/file/BYODDCcXusgxiDGLZhXBge/IDRCWebsite_Wireframes_v01?node-id=276%3A117).
- Resolves #7.
=> feat: add news (resolves #7)

src/_includes/layouts/projects.njk, src/scss/base/_typography.scss, src/scss/pages/_projects-tools.scss
Improves typestack (see #21).
Review typestack spacing on Projects & Tools and VTS pages.
Resolves #21.
=> fix: improve typestack (resolves #21)

_redirects, eleventy.config.js
Adds redirects file.
1. Visit deploy preview, test legacy URLs:
https://deploy-preview-25--idrc.netlify.app/about-the-idrc
https://deploy-preview-25--idrc.netlify.app/about-the-idrc/idrc-news
https://deploy-preview-25--idrc.netlify.app/about-the-idrc/idrc-news/534-continuing-our-work-during-covid-19
https://deploy-preview-25--idrc.netlify.app/about-the-idrc/idrc-news/533-we-count-removing-bias-and-exclusion-in-the-data-economy
https://deploy-preview-25--idrc.netlify.app/about-the-idrc/idrc-news/530-deep-2019-designing-enabling-economies-and-policies
https://deploy-preview-25--idrc.netlify.app/about-the-idrc/contact-us
https://deploy-preview-25--idrc.netlify.app/about-the-idrc/employment-opportunities
https://deploy-preview-25--idrc.netlify.app/about-the-idrc/getinvolved …
=> Add redirects (resolves #16)

eleventy.config.js, package-lock.json, package.json, src/_includes/layouts/base.njk, src/_includes/partials/global/meta-info.njk, src/service-worker.njk
Adds a service worker.
1. Test deploy preview.
**Expected behavior:** Service worker loads and precaches all routes except for `/admin/`.
Resolves #3.
=> feat: add service worker (resolves #3)

src/scss/pages/_home.scss
Fixes vertical scroll on homepage in the "What is Inclusive Design?" section.
1. Visit homepage.
**Expected behavior:** There's no vertical scroll on desktop.
Props @BlueSlug for the bug report!
Resolves #28.
=> fix: remove vertical scroll on homepage (resolves #28)

_redirects
Redirect www.* subdomains to the primary domain idrc.ocadu.ca
=> Redirect www.* to primary domain

src/scss/pages/_home.scss
This PR makes the scatterplot behaviour consistent according to designs.
1. Test home page in Chrome, Edge, Firefox, and Safari (desktop and mobile).
**Expected behavior:** Scatter plot should spill out of its container on both mobile and desktop browsers. There should be no horizontal scroll on mobile browsers.
Resolves #30.
=> fix: make scatter plot behaviour consistent across browsers (resolves #30)

src/404.md, src/_includes/layouts/base.njk, src/_includes/layouts/preview.njk, src/admin/config.yml, src/history.md, src/index.md, src/news.md, src/pages/about.md, src/pages/idrc-consulting.md, src/pages/philosophy.md, src/pages/vision-technology-service.md, src/projects-and-tools.md, src/scss/abstracts/_variables.scss, src/scss/base/_base.scss, src/scss/base/_typography.scss, src/scss/components/_brand.scss, src/scss/components/_nav.scss, src/scss/components/_pagination.scss, src/scss/components/_single-header.scss, src/scss/layout/_footer.scss, src/scss/layout/_header.scss, src/scss/pages/_404.scss, src/scss/pages/_generic.scss, src/scss/pages/_history.scss, src/scss/pages/_news-ideas.scss, src/team.md
Updates colour system to match [Figma](https://www.figma.com/file/i9bmZQt8dXqHcmbTgzmu0l/IDRCWebsite_Screens_2020?node-id=2%3A4217).
1. Inspect contents of [`_variables.scss`](https://github.com/inclusive-design/idrc/blob/2a7fea8409bd1e58e93491c887764392cad4943c/src/scss/abstracts/_variables.scss#L5-L19).
**Expected behavior:** Colours match those reflected in Figma.
Resolves #71.
=> feat: update colour system (resolves #71)

.eleventy.js
Removes precaching except for fonts and images, adds `clientsClaim` and `skipWaiting` configuration.
1. Deploy to production. 
**Expected behavior:** New versions load immediately.
https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.GenerateSW
Resolves #94.
=> fix: adjust server worker configuration (resolves #94)

.github/workflows/release.yml, CHANGELOG.md
This PR adds a GitHub Action which prepares GitHub releases based on commit messages.
1. Merge this PR.
**Expected behavior:** Once this PR is merged, a PR will be opened with a draft release.
See: https://github.com/google-github-actions/release-please-action
=> ci: add autoreleaser tool

src/_data/site.json
Updates the phone extension to `3967`
1. Open the site and ensure that the phone number in the footer mentions the extension as `3967`
=> fix: update phone number (Resolves #265)

package-lock.json, package.json, src/admin/config.yml
Indicate default color in color selectors.
1. Go to the Netlify CMS authoring interface at /admin/
2. Go to "Pages" collection, select any page, open "Header Background Color" selector, "Indigo 100 (Default)" is in the list.
3. Open other color selections, "(Default)" should be added to one color selection in the list.
=> GH-461: indicate default color in color selectors (resolves #461)

src/tools/clusive.md
=> Add Clusive in the tools section

.github/workflows/lighthouse.yml, .lighthouserc.js
Fix the failure when CI runs lighthouse audit tasks for mobile and desktop environment. The reported error is `Unable to connect to Chrome`.
1. Check the results of running lighthouse CI audit tasks for this pull request.
**Expected behavior:** 
These tasks should start without reporting the error.
See a discussion about fixing this error: https://github.com/GoogleChrome/lighthouse-ci/issues/799
=> fix: fix lighthouse CI failure

src/_includes/layouts/projects.njk
See #539 for details.
Resolves #539
=> Update projects listing to use project name (resolves #539)

package-lock.json, package.json
As the PR referenced has been merged and the branch removed, this PR updates `eleventy-plugin-fluid` to the main branch.
1. `npm install`
2. `npm start`
**Expected behavior:** Installs and builds.
=> chore(deps): switch to main branch of eleventy-plugin-fluid

src/_includes/layouts/resources.njk, src/_includes/partials/global/meta-info.njk
Some of the links were identified as broken when checklinks Netlify integration has run. This PR updates those links.
=> fix: update dead links

src/collections/projects/en-CA/financial-inclusion-from-the-community.md, src/collections/projects/en-CA/financial-inclusion-get-involved.md, src/collections/projects/en-CA/financial-inclusion.md
Add "Get Involved" and "From the Community" pages to the Financial Inclusion project.
=> Feat/financial inclusion: Add child pages for Financial Inclusion project

src/collections/projects/en-CA/financial-inclusion-from-the-community.md, src/collections/projects/en-CA/financial-inclusion-get-involved.md, src/collections/projects/en-CA/financial-inclusion.md
Resolve a merge conflict with financial-inclusion.md
=> chore: resolve content merge conflict

.github/workflows/lighthouse.yml, src/_includes/layouts/home.njk, src/assets/styles/pages/_home.scss
=> feat: update ACAW banner

src/collections/people/christian-martius.md
Updates the team by replacing Gloria with Christian
=> chore: update team members

src/collections/people/rachel-spence.md
To test, navigate to "/about/team/" and see Rachel is added to the team.
=> feat: add Rachel to the team

src/assets/styles/pages/_single.css, src/collections/news/ announcing-development-of-trust-meter-technical-specification.md, src/collections/news/announcing-development-of-trust-meter-technical-specification.md
1. Open the news items
2. See that the news item is the first in the list of news itesm
3. Open the news item
4. Ensure that it renders correctly with English and French versions. The French version should be wrapped in a `<div>` with `lang="fr"`.
**Expected behavior:**
=> chore: trust meter notice news item
